"""Gather every image of a character and stage it straight into the training set.

    python gather_character.py <char> [--cap N] [--apply]

Jeremy, 2026-09-22: "any set generated by the Laura Jen skill, I don't want to
individually review the pictures on the judging tab, I just want to move to
captioning. And each time you do the captioning, I want you to search for all of
the images of that character in the base folder in CNC info, and also in the
Codex outputs folders."

So this replaces stage_loragen.py: no judge set is built, and the sources are
discovered rather than passed in. Culling now happens on the preview page, where
the X button drops an image from the set.

Sources, in provenance order:
  1. cnc info/<char>/                      hand-collected (grok / OpenAI / misc)
  2. cnc info/codex/output/*<char>*/       older per-run folders
  3. cnc info/codex/outputs/*<char>*/      newer per-run folders (ash, hannah)
  4. cnc info/codex/outputs/*/<char>_*.png loose shots (keiko, trina) - the
                                           lora-gen-80 skill writes some runs flat

  5. cnc info/codex/references/<char>_*      the reference photos

References ARE staged, as of 2026-09-23 on Jeremy's instruction: they are the
cleanest images of each character that exist. They are kept whole beside the
Lora-Gen curriculum rather than ranked - four or five images cannot distort a set,
and they are what the identity embedding is built from, so each scores ~1.0
against itself and ranking them would be meaningless.

CPU only - InsightFace runs on the processor, so this is safe beside a training
or eval job. Nothing is written without --apply.
"""
import json
import re
import shutil
import sys
from pathlib import Path

import numpy as np
from PIL import Image

from sourcemode.gates.identity import _get_face_app

CHAR = sys.argv[1].lower()
APPLY = "--apply" in sys.argv
CAP = int(sys.argv[sys.argv.index("--cap") + 1]) if "--cap" in sys.argv else 100

BASE = Path("C:/Epic Games/Files/cnc info")
REFS = BASE / "codex/references"
DS = Path(f"outputs/lora-datasets/{CHAR}_v2")
IMG = DS / "image_src"
EXT = (".png", ".jpg", ".jpeg", ".webp")
# A folder can be named for a character and not contain her: "output/wrong bianca"
# holds four images of somebody else. Name-matching alone would stage them.
BAD_DIR = ("wrong", "bad", "reject", "discard", "dupe", "archive", "old_", "_old",
           "superseded")
# The identity metric is a weak per-image judge (AUC ~0.70) but a safe auto-reject
# below ~0.5 - use it only as that floor, never to rank or to choose.
MIN_SIM = 0.50
MIN_BUCKET_PX = 250   # below this a face is too small to train on - never staged


skipped_dirs: list[str] = []


def sources() -> list[tuple[Path, str]]:
    """(path, provenance) for every candidate image, de-duplicated by path."""
    seen, out = set(), []

    def take(p: Path, prov: str):
        if p.suffix.lower() in EXT and p.is_file() and p not in seen:
            seen.add(p); out.append((p, prov))

    # --loragen-only: Jeremy, 2026-10-04 (Cat, Jaina) - "ONLY pull their
    # LoRA-gen photos and photos from cnc info/codex/references". Stricter than
    # --no-base, which only drops the hand-collected base folder: cat has
    # ELEVEN older run folders carrying her name and --no-base still gathered
    # 336 images for her against jaina's clean 81.
    loragen_only = "--loragen-only" in sys.argv
    # --no-base: Jeremy, 2026-09-30 (Sienna) - only the references and the Lora-Gen
    # outputs are candidates; the hand-collected base folder is left out entirely.
    if not loragen_only and "--no-base" not in sys.argv:
        for p in sorted((BASE / CHAR).glob("*")) if (BASE / CHAR).is_dir() else []:
            take(p, "base")
    # Match the whole filename component before the first underscore, never a
    # substring: priya_ and priyanka_ are different people.
    for p in sorted(REFS.glob(f"{CHAR}_*")):
        if p.stem.split("_")[0].lower() == CHAR:
            take(p, "references")
    for root in ("output", "outputs"):
        d = BASE / "codex" / root
        if not d.is_dir():
            continue
        for sub in sorted(x for x in d.iterdir() if x.is_dir()):
            if any(b in sub.name.lower() for b in BAD_DIR):
                skipped_dirs.append(f"{root}/{sub.name}")
                continue
            # The hyphen matters: `2026-07-26_cat_lora60_1` contains "lora" and
            # is one of eleven older cat runs; `lora-gen-80` is the shot plan.
            if loragen_only and "lora-gen" not in sub.name.lower():
                skipped_dirs.append(f"{root}/{sub.name}")
                continue
            if CHAR in sub.name.lower():           # a whole run folder for this character
                for p in sorted(sub.glob("*")):
                    take(p, f"{root}/{sub.name}")
                continue
            # A shared run folder (lora-gen-80) holds BOTH layouts and the skill picks
            # one per run with no rule: keiko/trina/bianca/geena are loose files at the
            # top, ash and hannah are in a subfolder named for them. Searching only for
            # loose files missed all 80 of Ash's shots and would have trained her on
            # the 23 images in her base folder.
            # ...and a subfolder may be named for her and the run: gabi's hair
            # top-up landed in `lora-gen-80/gabi-hair-topup-2026-10-06`, which an
            # exact `<char>` match missed entirely. Whole name component before
            # the first - or _ only: priya- must not take priyanka-.
            for nested in sorted(x for x in sub.iterdir() if x.is_dir()):
                if re.split(r"[-_]", nested.name.lower())[0] != CHAR:
                    continue
                if any(b in nested.name.lower() for b in BAD_DIR):
                    skipped_dirs.append(f"{root}/{sub.name}/{nested.name}")
                    continue
                for p in sorted(nested.rglob("*")):
                    take(p, f"{root}/{sub.name}/{nested.name}")
            for p in sorted(sub.glob(f"{CHAR}_*")):
                take(p, f"{root}/{sub.name} (loose)")
    return out


# A staged set is ADDED TO, never skipped. This used to exit at once with
# "already staged; nothing to do" whenever image_src had anything in it - so
# Casey's second chain run, queued at cap 190 to bring in her older folders,
# staged nothing and said nothing (2026-10-08). Now the sources are listed (a
# file walk, no model), anything not yet in the manifest is measured, and only a
# run that finds nothing new stops here. Staged images keep their numbers.
# --force re-measures everything and clears the captions, as before.
man = json.loads((DS/"manifest.json").read_text(encoding="utf-8")) if (DS/"manifest.json").is_file() else []
staged_before = {m.get("original") for m in man}
n_staged = len(list(IMG.glob("src_*.png"))) if IMG.is_dir() else 0
SRC = sources()
ONLY_NEW = None
if n_staged and "--force" not in sys.argv:
    # what an earlier run already measured and rejected is not "new" either
    _prev = json.loads((DS/"candidates_all.json").read_text(encoding="utf-8")) \
        if (DS/"candidates_all.json").is_file() else {}
    prior_rejected = _prev.get("rejected", [])
    rejected_before = {(r["file"], r["prov"]) for r in prior_rejected}
    ONLY_NEW = [(p, prov) for p, prov in SRC
                if str(p) not in staged_before and (p.name, prov) not in rejected_before]
    if not ONLY_NEW:
        print(f"{CHAR}: already staged ({n_staged} images); no new images in any source; nothing to do")
        print("GATHERDONE")
        raise SystemExit(0)
    print(f"{CHAR}: {n_staged} already staged; {len(ONLY_NEW)} new candidates to measure "
          f"for the {max(0, CAP - n_staged)} slots left under cap {CAP}")

# --force RE-STAGES and RENUMBERS src_NNN.png. Captions written against the old
# numbering then describe a different photograph, silently: Amanda ended up with 75
# captions over 80 images and five provably attached to the wrong picture. A caption
# is only ever valid for the exact staging that produced it, so clear them here and
# let the captioner run again.
if "--force" in sys.argv and IMG.is_dir():
    stale = sorted(IMG.glob("*.txt"))
    if stale:
        bin_ = DS / "_stale_captions"
        bin_.mkdir(parents=True, exist_ok=True)
        for t in stale:
            t.replace(bin_ / t.name)
        print(f"  --force renumbers the staging, so {len(stale)} caption(s) are now stale "
              f"-> moved to {bin_.name}; re-run the captioner")

app = _get_face_app()
ref = []
for p in sorted(REFS.glob(f"{CHAR}_*")):
    if p.suffix.lower() in EXT:
        fs = app.get(np.asarray(Image.open(p).convert("RGB"))[:, :, ::-1])
        if fs:
            ref.append(max(fs, key=lambda x: (x.bbox[2]-x.bbox[0])*(x.bbox[3]-x.bbox[1])).normed_embedding)
if not ref:
    raise SystemExit(f"{CHAR}: no usable reference photos in {REFS} - cannot score identity")
Rm = np.stack(ref).mean(0); Rm /= np.linalg.norm(Rm)

# Every OTHER character's references, so a candidate can be compared against the
# whole cast rather than a single floor. Built once; it is 188 embeddings.
OTHERS = {}
for p in sorted(REFS.glob("*")):
    if p.suffix.lower() not in EXT:
        continue
    who = p.stem.split("_")[0].lower()
    if who in (CHAR, "universal"):
        continue
    fs = app.get(np.asarray(Image.open(p).convert("RGB"))[:, :, ::-1])
    if fs:
        e = max(fs, key=lambda x: (x.bbox[2]-x.bbox[0])*(x.bbox[3]-x.bbox[1])).normed_embedding
        OTHERS.setdefault(who, []).append(e)
OTHER_M = {w: (np.stack(v).mean(0) / np.linalg.norm(np.stack(v).mean(0)))
           for w, v in OTHERS.items()}
print(f"  cross-check bank: {len(OTHER_M)} other identities")


def impostor(emb):
    """The character whose references beat CHAR's on this face, or None."""
    mine = float(emb @ Rm)
    best, score = None, mine
    for w, m in OTHER_M.items():
        v = float(emb @ m)
        if v > score:
            best, score = w, v
    return (best, mine, score) if best else None

rows, reject = [], []
for p, prov in (SRC if ONLY_NEW is None else ONLY_NEW):
    try:
        im = Image.open(p).convert("RGB")
    except Exception as e:  # noqa: BLE001
        reject.append((p.name, prov, f"unreadable: {e}")); continue
    fs = app.get(np.asarray(im)[:, :, ::-1])
    if not fs:
        reject.append((p.name, prov, "no face")); continue
    if len(fs) > 1:
        # a second face teaches the trigger to paint two people
        reject.append((p.name, prov, f"{len(fs)} faces")); continue
    f = fs[0]
    sim = float(f.normed_embedding @ Rm)
    # Relative check before the floor: a near-miss clears 0.50 easily. 35 of Ash's
    # shots were Hannah at 0.51-0.62 against Ash and 0.69-0.90 against Hannah.
    imp = impostor(f.normed_embedding)
    if imp is not None:
        who, mine, theirs = imp
        reject.append((p.name, prov,
                       f"looks like {who} ({theirs:.2f}) more than {CHAR} ({mine:.2f})"))
        continue
    if sim < MIN_SIM:
        reject.append((p.name, prov, f"identity {sim:.2f} below the {MIN_SIM} floor")); continue
    fw, fh = float(f.bbox[2]-f.bbox[0]), float(f.bbox[3]-f.bbox[1])
    bucket = round(fh / im.height * (1536 if im.height > im.width else 1024))
    # Jeremy, 2026-09-29: "unless they are REALLY small in which case just don't put
    # them in the set." A face under MIN_BUCKET_PX at the training bucket carries too
    # little detail to learn from and was only ever reaching him as a flag to dismiss.
    # Measured across the six live sets this drops 0-6 images each. Note bucket is
    # keyed on face HEIGHT, which is pose-invariant - width shrinks with yaw and a
    # width-keyed rule silently penalises turned heads.
    if bucket < MIN_BUCKET_PX:
        reject.append((p.name, prov, f"face {bucket}px at the bucket, under {MIN_BUCKET_PX}")); continue
    rows.append({"original": str(p), "prov": prov, "sim": round(float(f.normed_embedding @ Rm), 3),
                 "face_px": int(fw), "bucket_px": bucket, "w": im.width, "h": im.height,
                 "yaw": round(float(f.pose[1]), 1), "pitch": round(float(f.pose[0]), 1),
                 "face_h_frac": round(fh/im.height, 3)})

# The Lora-Gen set comes FIRST, whatever it scores. Those 80 shots are a designed
# curriculum - 28 tight head, 14 head-and-shoulders, 26 head-and-chest, 12 waist-up,
# with a deliberate yaw spread - and ranking the whole pool on identity throws that
# away: Bianca's 113 hand-collected photos score a median 0.879 against her
# generated shots and would have taken 100 of the 100 slots, leaving a set with no
# angle coverage and a 353px median face, 29 of them under the 300px floor.
# Everything else competes for the remaining slots on identity, then face size.
def is_loragen(r):
    # References ride with the designed set: always in, never ranked.
    return "lora-gen" in r["prov"] or r["prov"] == "references"


designed = [r for r in rows if is_loragen(r)]
others = sorted((r for r in rows if not is_loragen(r)),
                key=lambda r: (-r["sim"], -r["bucket_px"]))
designed.sort(key=lambda r: r["original"])
# adding to a staged set: the cap counts what is already there
slots = max(0, CAP - n_staged) if ONLY_NEW is not None else CAP
keep = (designed + others)[:slots]
spill = (designed + others)[slots:]

by_prov: dict[str, int] = {}
for r in rows:
    by_prov[r["prov"]] = by_prov.get(r["prov"], 0) + 1
print(f"{CHAR}: {len(rows)} measured, {len(reject)} rejected, staging {len(keep)} (cap {CAP})")
print(f"  references scored: {len(ref)} (staged as candidates)")
for k, v in sorted(by_prov.items(), key=lambda kv: -kv[1]):
    print(f"    {v:4}  {k}")
if keep:
    nd = sum(1 for r in keep if is_loragen(r))
    print(f"  staged: {nd} Lora-Gen shots (kept whole) + {len(keep) - nd} others by rank")
    sims = sorted(r["sim"] for r in keep); px = sorted(r["bucket_px"] for r in keep)
    print(f"  staged identity median {sims[len(sims)//2]:.3f} (min {sims[0]:.3f})")
    print(f"  staged face at bucket median {px[len(px)//2]}px, under 300px: {sum(1 for x in px if x < 300)}")
why: dict[str, int] = {}
for _, _, r in reject:
    k = r.split(":")[0]
    why[k] = why.get(k, 0) + 1
if why:
    print("  rejected: " + ", ".join(f"{v} {k}" for k, v in sorted(why.items(), key=lambda kv: -kv[1])))
if spill:
    print(f"  {len(spill)} over the cap, recorded in candidates_all.json but not staged")
for d in skipped_dirs:
    print(f"  SKIPPED FOLDER {d} - name marks it as not this character")

if not APPLY:
    print("\nDRY RUN - add --apply to stage")
    raise SystemExit(0)

IMG.mkdir(parents=True, exist_ok=True)
nxt = max((int(p.stem.split("_")[1]) for p in IMG.glob("src_*.png")), default=-1) + 1
man = json.loads((DS/"manifest.json").read_text(encoding="utf-8")) if (DS/"manifest.json").is_file() else []
staged_before = {m.get("original") for m in man}
geom = {}
for r in keep:
    if r["original"] in staged_before:
        continue
    dest = IMG / f"src_{nxt:03d}.png"
    Image.open(r["original"]).convert("RGB").save(dest)
    man.append({"file": dest.name, "original": r["original"], "batch": r["prov"],
                "sim": r["sim"], "bucket_px": r["bucket_px"]})
    geom[dest.name] = {k: r[k] for k in ("face_h_frac", "face_px", "yaw", "pitch", "w", "h")}
    nxt += 1
(DS/"manifest.json").write_text(json.dumps(man, indent=1), encoding="utf-8")
prior = json.loads((DS/"geometry.json").read_text(encoding="utf-8")) if (DS/"geometry.json").is_file() else {}
(DS/"geometry.json").write_text(json.dumps({**prior, **geom}, indent=1), encoding="utf-8")
# an incremental run keeps the earlier rejects on record, so they are not re-measured next time
(DS/"candidates_all.json").write_text(json.dumps({"kept": keep, "over_cap": spill,
    "rejected": (prior_rejected if ONLY_NEW is not None else [])
                + [{"file": a, "prov": b, "why": c} for a, b, c in reject]}, indent=1), encoding="utf-8")
print(f"\nstaged {len(geom)} new into {IMG} (set now {len(list(IMG.glob('src_*.png')))})")
print("GATHERDONE")
